#!/usr/bin/env node

const fs = require("fs")
const net = require("net");
const path = require("path")
const config = require("./config");

process.argv.splice(1, 1);

process.argv[1] = path.resolve(process.argv[1]);

var client = new net.Socket();

console.log(process.argv[1]);


client.connect(config.server.port, function () {
    client.write(fs.readFileSync(process.argv[1]));
});

client.on('data', function (data) {
    console.log(data.toString());
    client.destroy();
    // process.exit(1)
});

client.on('error', function (data) {
    // console.log(data);
    // client.destroy();
    // process.exit(1)
});